# TODO https://github.com/alacritty/alacritty/issues/4754

[general]
import = [
	"~/.config/alacritty/appearance.toml",
	"~/.config/alacritty/env.toml",
	"~/.config/alacritty/bindings.toml",
	"~/.config/alacritty/host.toml",
]

[terminal]
osc52 = "CopyPaste"
