exclusionRules:
  - pattern: https?://mail.google.com/*
  - pattern: https?://mail.proton.me/*
  - pattern: https?://docs.google.com/*
  - pattern: https?://127.0.0.0:8006/*
  - pattern: https?://127.0.0.1:8080/*
  - pattern: https?://10.2.0.1/*
  - pattern: https?://10.2.0.2/*
grabBackFocus: true
keyMappings: |-
  unmapAll

  map j scrollDown
  map J scrollRight
  map k scrollUp
  map K scrollLeft

  map gg scrollToTop
  map G scrollToBottom

  map d scrollPageDown
  map <c-d> scrollPageDown
  map u scrollPageUp
  map <c-u> scrollPageUp

  map r reload
  map R reload hard

  map yy copyCurrentUrl

  map p openCopiedUrlInCurrentTab
  map P openCopiedUrlInNewTab

  map i enterInsertMode

  map v enterVisualMode
  map V enterVisualLineMode

  map I passNextKey

  map gi focusInput
  map gn goNext
  map gp goPrevious
  map gr goToRoot
  map gu goUp

  map f  LinkHints.activateMode
  map F  LinkHints.activateModeToOpenInNewForegroundTab
  map tf LinkHints.activateModeToOpenInNewTab
  map q  LinkHints.activateModeWithQueue

  map Wf LinkHints.activateModeToOpenIncognito

  map ;d LinkHints.activateModeToDownloadLink
  map ;y LinkHints.activateModeToCopyLinkUrl

  map o  Vomnibar.activate
  map O  Vomnibar.activateInNewTab

  map b  Vomnibar.activateBookmarks
  map B  Vomnibar.activateBookmarksInNewTab

  map S Vomnibar.activateTabSelection

  map e Vomnibar.activateEditUrl
  map E Vomnibar.activateEditUrlInNewTab

  map / enterFindMode

  map n performFind
  map N performBackwardsFind

  map * findSelected
  map # findSelectedBackwards

  map H goBack
  map L goForward

  map tt createTab
  map ww createTab window
  map WW createTab incognito
  map Ww createTab incognito

  map h previousTab
  map l nextTab

  map s visitPreviousTab

  map td duplicateTab

  map x removeTab
  map X restoreTab

  map tg moveTabToNewWindow

  map ch closeTabsOnLeft
  map cl closeTabsOnRight
  map co closeOtherTabs

  map <c-h> moveTabLeft
  map <c-l> moveTabRight

  map + zoomIn
  map - zoomOut
  map = zoomReset

  map ? showHelp
linkHintCharacters: pgcraoeuhtnsqjkmwvz
regexFindMode: true
scrollStepSize: 30
searchEngines: |-
  ap: https://archlinux.org/packages/?q=%s Arch Packages
  au: https://aur.archlinux.org/packages?K=%s AUR Packages
  aw: https://wiki.archlinux.org/index.php?search=%s Arch Wiki
  d: https://duckduckgo.com/?q=%s DuckDuckGo
  di: https://duckduckgo.com/?iar=images&q=%s DuckDuckGo Images
  g: https://www.google.com/search?q=%s Google
  gi: https://images.google.com/search?q=%s Google Images
  pd: https://www.protondb.com/search?q=%s Proton DB
  sd: https://steamdb.info/instantsearch/?query=%s Steam DB
  ss: https://store.steampowered.com/search/?term=%s Steam Store
  w: https://www.wikipedia.org/w/index.php?title=Special:Search&search=%s Wikipedia
  y: https://www.youtube.com/results?search_query=%s Youtube
settingsVersion: "2.4"
userDefinedLinkHintCss: |-2
STYLESHEET:
